[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_pretty_print"
repository.workspace = true
version              = "0.0.0"


[dependencies]
pgt_pretty_print_codegen.workspace = true
pgt_query.workspace                = true

[dev-dependencies]
camino.workspace                 = true
dir-test.workspace               = true
insta.workspace                  = true
pgt_statement_splitter.workspace = true
