[package]
edition = "2021"
name    = "xtask_codegen"
publish = false
version = "0.0.0"

[dependencies]
anyhow           = { workspace = true }
bpaf             = { workspace = true, features = ["derive"] }
convert_case     = { workspace = true }
pgls_analyse     = { workspace = true }
pgls_analyser    = { workspace = true }
pgls_diagnostics = { workspace = true }
pgls_env         = { workspace = true }
pgls_pglinter    = { workspace = true }
pgls_schema_cache = { workspace = true, features = ["schema"] }
pgls_splinter    = { workspace = true }
pgls_workspace   = { workspace = true, features = ["schema"] }
schemars         = { workspace = true }
proc-macro2      = { workspace = true, features = ["span-locations"] }
pulldown-cmark   = { version = "0.12.2" }
quote            = "1.0.36"
regex            = "1.11"
xtask            = { path = '../', version = "0.0" }
